CREATE DATABASE IF NOT EXISTS PROYECTO;
USE PROYECTO;

CREATE TABLE IF NOT EXISTS USUARIOS(
    ID          INT AUTO_INCREMENT NOT NULL,
    NOMBRE      VARCHAR(50) NOT NULL,
    APELLIDOS   VARCHAR(100),
    EMAIL       VARCHAR(255) NOT NULL,
    PASSWORD    VARCHAR(255) NOT NULL,
    FECHA       DATE NOT NULL,
    CONSTRAINT  pk_usuarios PRIMARY KEY(ID),
    CONSTRAINT  uq_email UNIQUE(email)
) ENGINE=InnoDb;

CREATE TABLE IF NOT EXISTS NOTAS(
    ID          INT AUTO_INCREMENT NOT NULL,
    ID_USER     INT NOT NULL,
    TITULO      VARCHAR(50),
    DESCRIPCION TEXT,
    FECHA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT  pk_notas PRIMARY KEY(ID),
    CONSTRAINT  fk_usuarios FOREIGN KEY(ID_USER) REFERENCES USUARIOS(ID)
) ENGINE=InnoDb;